---

# PLAYBOOK: ydb_platform.ydb.restart
# PROPOSE : This playbook is designed for safe restart for the cluster
#           
# EXAMPLE:
#
# Restart all nodes
#   ansible-playbook ydb_platform.ydb.restart
#
# Restart all nodes on the host
#   ansible-playbook ydb_platform.ydb.restart -l <HostFQDN>
#
# Restart all storage nodes
#   ansible-playbook ydb_platform.ydb.restart -t storage
#
# Restart all dnyamic nodes
#   ansible-playbook ydb_platform.ydb.restart -t dynamic
#

- hosts: "{{ playbook_hosts | default('ydb') }}"
  become: true

  roles:
  - role: ydbd_rolling_static
    availability_mode: force
    tags:
      - storage
      - static

  - role: ydbd_rolling_dynamic
    tags:
      - database
      - dynamic
